# Preparação dos dados

In [18]:
import pandas as pd

caminho = r'C:\Users\saulosgil\OneDrive\Documentos\health_outcomes_workers\data\df.xlsx'
df = pd.read_excel(caminho)

# Quantas linhas e colunas existem?
print(f'O número de linhas e colunas do dataset é: {df.shape[0]} linhas e {df.shape[1]} colunas')
print(80 *'-')

print("Colunas da base:")
print(df.columns)
print(80 *'-')

print("Tipos de dados:")
print(df.dtypes)
print(80 *'-')

print("Quantidade de valores ausentes por coluna:")
print(df.isna().sum())
print(80 *'-')

print("\nNúmero de linhas duplicadas:", df.duplicated().sum())

O número de linhas e colunas do dataset é: 44 linhas e 66 colunas
--------------------------------------------------------------------------------
Colunas da base:
Index(['unidade', 'idade ', 'sexo', 'estado_civil', 'escolaridade',
       'renda_mensal', 'n_pessoas_domicilio', 'tipo_moradia', 'tempo_moradia',
       'cor_raca', 'tempo_trab_anos', 'funcao_trab', 'carga_horaria_horas_sem',
       'forma_remuneracao', 'outro_trab', 'ja_trab_outro_local_reciclagem',
       'utiliza_epi', 'quais_epis', 'recebe_treino_segurança',
       'ja_sofreu_acid_trab', 'percepcao_condicoes_trab',
       'exposicao_percebida', 'tabacco', 'bebida', 'freq_bebida',
       'diagnostico', 'acompanhamento_medico', 'medicamentos',
       'como_avalia_propria_saude', 'who1', 'who2', 'who3', 'who4', 'who5',
       'who6', 'who7', 'who8', 'who9', 'who10', 'who11', 'who12', 'who13',
       'who14', 'who15', 'who16', 'who17', 'who18', 'who19', 'who20', 'who21',
       'who22', 'who23', 'who24', 'who25', 'who26', 'peso', 'estatura', 'imc',
       'imc_classe', 'circun_abdome', 'circun_pant', 'pas', 'pad', 'hgs_dir',
       'hgs_esq', 'cintura_quadril_ratio'],
      dtype='str')
--------------------------------------------------------------------------------
Tipos de dados:
unidade                      str
idade                      int64
sexo                         str
estado_civil                 str
escolaridade                 str
                          ...
pas                        int64
pad                        int64
hgs_dir                  float64
hgs_esq                  float64
cintura_quadril_ratio    float64
Length: 66, dtype: object
--------------------------------------------------------------------------------
Quantidade de valores ausentes por coluna:
unidade                  0
idade                    0
sexo                     0
estado_civil             0
escolaridade             0
                        ..
pas                      0
pad                      0
hgs_dir                  0
hgs_esq                  0
cintura_quadril_ratio    0
Length: 66, dtype: int64
--------------------------------------------------------------------------------

Número de linhas duplicadas: 0

In [19]:
df.head(5)

,unidade,idade,sexo,estado_civil,escolaridade,renda_mensal,n_pessoas_domicilio,tipo_moradia,tempo_moradia,cor_raca,...,estatura,imc,imc_classe,circun_abdome,circun_pant,pas,pad,hgs_dir,hgs_esq,cintura_quadril_ratio
0,matriz,34,feminino,separado,médio completo,1 a 3 salários mínimos,6,própria,33 anos,preto (a),...,1.60,33.95,obesidade grau I,96.0,45.0,120,90,29.8,23.0,60.000000
1,matriz,59,masculino,divorciado,médio completo,mais de 3 salários,2,própria,6 anos,pardo (a),...,1.57,25.96,sobrepeso,82.0,39.0,110,70,22.9,31.2,52.229299
2,matriz,27,masculino,solteiro,superior completo,mais de 3 salários,4,alugada,10 anos,pardo (a),...,1.76,34.70,obesidade grau I,102.0,44.0,130,90,37.2,46.3,57.954545
3,matriz,40,masculino,solteiro,médio completo,1 a 3 salários mínimos,1,alugada,10 anos,preto (a),...,1.69,20.66,eutrófico,78.0,35.5,110,80,41.5,41.3,46.153846
4,matriz,23,masculino,solteiro,médio completo,mais de 3 salários,2,própria,1 ano,preto (a),...,1.83,21.74,eutrófico,86.5,38.0,120,70,40.7,42.7,47.267760

In [20]:
df.tail(5)

,unidade,idade,sexo,estado_civil,escolaridade,renda_mensal,n_pessoas_domicilio,tipo_moradia,tempo_moradia,cor_raca,...,estatura,imc,imc_classe,circun_abdome,circun_pant,pas,pad,hgs_dir,hgs_esq,cintura_quadril_ratio
39,matriz,65,masculino,casado,fundamental incompleto,1 a 3 salários mínimos,5,cedida,25 anos,pardo (a),...,1.63,26.08,sobrepeso,86.0,36.0,120,80,44.4,36.5,52.760736
40,matriz,41,masculino,solteiro,fundamental incompleto,1 a 3 salários mínimos,4,cedida,27 anos,pardo (a),...,1.64,24.39,eutrófico,85.0,36.0,120,80,22.5,27.5,51.829268
41,matriz,47,masculino,casado,fundamental incompleto,sem renda,5,alugada,36 anos,amarelo (a),...,1.67,30.01,obesidade grau I,99.0,41.0,120,80,40.2,29.4,59.281437
42,matriz,29,feminino,casado,superior completo,mais de 3 salários,3,própria,29 anos,pardo (a),...,1.67,30.94,obesidade grau I,90.0,42.0,130,80,29.7,31.0,53.892216
43,matriz,18,masculino,solteiro,fundamental incompleto,1 a 3 salários mínimos,3,própria,17 anos,pardo (a),...,1.76,19.82,eutrófico,72.5,33.0,120,70,35.9,35.2,41.193182